args:
  bl: 0.14962844133819508
  camera:
    cx: 968.639274597168
    cy: 560.599250793457
    fx: 565.1982237574123
    fy: 565.1982237574123
  data_config_file: /app/FDCPost/config/test_config.yaml
  format: png
name: down
type: GeneralStereo
